CREATE TABLE BLOG_POSTS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    CONTENT CLOB NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    --AUTHOR_ID NUMBER REFERENCES USERS(ID),
    STATUS VARCHAR2(20) DEFAULT 'DRAFT',
    image_url VARCHAR2(255)
);


ALTER TABLE BLOG_POSTS
ADD image_url VARCHAR2(255);

update BLOG_POSTS
set image_url = 
'img/projekte/512px-BI_5_Boehringer_Ingelheim.jpg'
;   


INSERT INTO BLOG_POSTS (TITLE, CONTENT, CREATED_AT, STATUS) 
VALUES ('Der Beginn eines Abenteuers', 'Dies ist der erste Blog-Eintrag. Hier wird beschrieben, wie alles begann.', TO_DATE('2023-01-05', 'YYYY-MM-DD'), 'PUBLISHED');

INSERT INTO BLOG_POSTS (TITLE, CONTENT, CREATED_AT, STATUS) 
VALUES ('Tipps für erfolgreiches Bloggen', 'Erfolgreiches Bloggen erfordert Engagement und eine klare Strategie. Hier sind einige Tipps.', TO_DATE('2023-02-12', 'YYYY-MM-DD'), 'PUBLISHED');

INSERT INTO BLOG_POSTS (TITLE, CONTENT, CREATED_AT, STATUS) 
VALUES ('Reisebericht: Ein Tag in Berlin', 'Berlin ist eine Stadt voller Kultur und Geschichte. In diesem Beitrag schildere ich meinen Tag dort.', TO_DATE('2023-03-22', 'YYYY-MM-DD'), 'PUBLISHED');

INSERT INTO BLOG_POSTS (TITLE, CONTENT, CREATED_AT, STATUS) 
VALUES ('Technologie im Wandel', 'Die Technologielandschaft verändert sich rasant. Was können wir in den nächsten Jahren erwarten?', TO_DATE('2023-04-30', 'YYYY-MM-DD'), 'DRAFT');

INSERT INTO BLOG_POSTS (TITLE, CONTENT, CREATED_AT, STATUS) 
VALUES ('Warum Lesen wichtig ist', 'In einer Welt voller Ablenkungen ist das Lesen wichtiger denn je. Hier sind meine Gedanken dazu.', TO_DATE('2023-05-15', 'YYYY-MM-DD'), 'PUBLISHED');

INSERT INTO BLOG_POSTS (TITLE, CONTENT, CREATED_AT, STATUS) 
VALUES ('Wie man ein Startup gründet', 'Ein Startup zu gründen ist keine leichte Aufgabe. Dieser Beitrag beschreibt die ersten Schritte.', TO_DATE('2023-06-10', 'YYYY-MM-DD'), 'PUBLISHED');

INSERT INTO BLOG_POSTS (TITLE, CONTENT, CREATED_AT, STATUS) 
VALUES ('Die Zukunft des E-Commerce', 'E-Commerce wächst stetig. Was erwartet uns in der Zukunft dieses spannenden Bereichs?', TO_DATE('2023-07-19', 'YYYY-MM-DD'), 'DRAFT');

INSERT INTO BLOG_POSTS (TITLE, CONTENT, CREATED_AT, STATUS) 
VALUES ('Fotografie für Anfänger', 'Fotografie kann eine großartige Möglichkeit sein, die Welt um uns herum zu erkunden. Hier sind einige Tipps für Anfänger.', TO_DATE('2023-08-04', 'YYYY-MM-DD'), 'PUBLISHED');

INSERT INTO BLOG_POSTS (TITLE, CONTENT, CREATED_AT, STATUS) 
VALUES ('Gesunde Ernährung leicht gemacht', 'Gesunde Ernährung muss nicht kompliziert sein. Hier sind einige einfache Tipps, um gesünder zu essen.', TO_DATE('2023-09-12', 'YYYY-MM-DD'), 'PUBLISHED');

INSERT INTO BLOG_POSTS (TITLE, CONTENT, CREATED_AT, STATUS) 
VALUES ('Erfolgreiche Selbstorganisation', 'Sich selbst zu organisieren ist der Schlüssel zu Erfolg und Produktivität. Dieser Beitrag gibt praktische Ratschläge.', TO_DATE('2023-10-03', 'YYYY-MM-DD'), 'PUBLISHED');


select * from BLOG_POSTS
;



SELECT ID, TITLE, SUBSTR(CONTENT, 1, 200) AS SUMMARY, CREATED_AT
FROM BLOG_POSTS
ORDER BY CREATED_AT DESC;