-- -----------------------------------------------------------------------------------------------------------------------------
-- Nodes
-- -----------------------------------------------------------------------------------------------------------------------------

create table NODES
(
  id              number generated by default as identity primary key
, parent_id       number
, name            varchar2(255) null
, content         varchar2(4000)
, big_content     clob
, format_name     varchar2(100)
, format_content  varchar2(100)
, seq             number
, constraint fk_parent foreign key 
    ( parent_id ) references NODES ( id )
)
;

create unique index udx_nodes on NODES
( parent_id
, name )
;

create or replace view nodes_hierarchy as
with hierarchy as 
(
  select
    n.id
  , n.parent_id
  , n.name
  , n.content
  , n.format_name
  , n.format_content
  , decode( n.format_name, null, n.name, replace( n.format_name, '@', n.name ) ) formatted_name
  , decode( n.format_content, null, n.content, replace( n.format_content, '@', n.content ) ) formatted_content
  , n.big_content
  , n.seq
  , level as node_level
  , sys_connect_by_path( n.name, '\' ) as node_path
  from
    nodes n
  start with
    n.parent_id is null
  connect by
    prior n.id = n.parent_id
  order siblings by
    n.seq
)
select
  h.*
, nvl( p.node_path, '\' ) as parent_path
from
  hierarchy h
left join
  hierarchy p on h.parent_id = p.id
;



    
select * from nodes_hierarchy
--where name = 'Impressum'
;
    
-- -----------------------------------------------------------------------------------------------------------------------------
-- Daten:
-- -----------------------------------------------------------------------------------------------------------------------------

--delete nodes;
     
-- Wurzelknoten "Profile" einfügen
INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
values (NULL, 'Profile', NULL, NULL, NULL, 10);

-- "APEX Developer 1.0.0" als Kind von "Profile" einfügen
INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
values ((SELECT id FROM nodes WHERE name = 'Profile'), 'APEX Developer 1.0.0', NULL, NULL, NULL, 10);

-- "Titelseite" als Kind von "APEX Developer 1.0.0" einfügen
INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
values ((SELECT id FROM nodes WHERE name = 'APEX Developer 1.0.0'), 'Titelseite', NULL, NULL, NULL, 10);

-- "Expertise" als Kind von "APEX Developer 1.0.0" einfügen
INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
values ((SELECT id FROM nodes WHERE name = 'APEX Developer 1.0.0'), 'Expertise', NULL, NULL, NULL, 20);

-- "Projekte" als Kind von "APEX Developer 1.0.0" einfügen
INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
values ((SELECT id FROM nodes WHERE name = 'APEX Developer 1.0.0'), 'Projekte', NULL, NULL, NULL, 30);

commit;

-- -----------------------------------------------------------------------------------------------------------------------------
-- Knoten fpr \Profile\APEX Developer 1.0.0\Titelseite: 
-- -----------------------------------------------------------------------------------------------------------------------------

-- INSERT-Anweisungen für Unterknoten von "\Profile\APEX Developer 1.0.0\Titelseite"
INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Profil', 'Marcus Kühl', '<h1 class="profil">@</h1>', '<h1 class="profil">@</h1>', 10
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Tätigkeit 01', 'Senior Oracle Developer', ' ', '<h2 class="profil">@</h2>', 20
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Tätigkeit 02', 'Oracle Apex Developer', ' ', '<h2 class="profil">@</h2>', 30
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Leer', '<br\>', ' ', NULL, 40
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Adresse', 'Odinstraße 24<br\>10318 Berlin', NULL, NULL, 50
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Email', 'office.kuehl@posteo.de', NULL, NULL, 60
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Telefon', '+49 (0)176 99 21 95 05', NULL, NULL, 70
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Qualifikation', 'Senior Oracle Developer, <br\>APEX Developer', NULL, NULL, 80
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Ausbildung', 'Dipl. Geologe CAU Kiel', NULL, NULL, 90
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Geburtsdatum', '12.04.1966', NULL, NULL, 100
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Staatsangehörigkeit', 'Deutsch', NULL, NULL, 110
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Sprachen', 'Deutsch, Englisch, Spanisch', NULL, NULL, 120
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Titelseite'; 

commit;

-- -----------------------------------------------------------------------------------------------------------------------------
-- \Profile\APEX Developer 1.0.0\Expertise
-- -----------------------------------------------------------------------------------------------------------------------------
 
-- Neue INSERT-Anweisungen für Knoten unter "\Profile\APEX Developer 1.0.0\Expertise"
INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Oracle APEX', NULL, NULL, NULL, 10
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'Datenbank', NULL, NULL, NULL, 20
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'SQL', NULL, NULL, NULL, 30
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise';


INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
SELECT id, 'PL/SQL', NULL, NULL, NULL, 40
FROM nodes_hierarchy WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise';


commit;

-- -----------------------------------------------------------------------------------------------------------------------------
-- \Profile\APEX Developer 1.0.0\Expertise\Oracle Application Express
-- -----------------------------------------------------------------------------------------------------------------------------

UPDATE nodes
SET content = '<p>APEX Version 3 bis 24.1</p>
<p>Entwicklung verschiedener Anwendungen</p>
<p>Anwendungsdesign in Absprache mit Fachabteilungen des Kunden, Anpassung des APEX Templates</p>
<p>Entwicklung komplexer Seiten, Views zum Aufbau komplexer Reports in APEX, dynamischer Anwendungsmenüs, u.s.w.</p>
<p>User-defined Authentication / Authorization</p>
<p>REST Data Services</p>
<p>Single Sign On (LDAP)</p>
<p>Social Sign In</p>
<p>Dynamic Actions</p>
<p>Javascript, CSS, HTML</p>
<p>File-Upload / Download</p>
<p>Template-Anpassung / Erweiterungen</p>
<p>Mails Templates, Mail Versand</p>
<p>APEX Universal Theme</p>'
WHERE id = (
    SELECT id
    FROM nodes_hierarchy
    WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise\Oracle APEX'
);

-- Überprüfung des Ergebnisses
SELECT node_path, name, content
FROM nodes_hierarchy
WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise\Oracle APEX';

commit;


-- -----------------------------------------------------------------------------------------------------------------------------
-- \Profile\APEX Developer 1.0.0\Expertise\Oracle Datenbank
-- -----------------------------------------------------------------------------------------------------------------------------


UPDATE nodes
SET content = '<p>Oracle 7 – 23</p>
<p>Oracle Cloud Autonomous Database (OCI)</p>'
WHERE id = (
    SELECT id
    FROM nodes_hierarchy
    WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise\Datenbank'
);

-- Überprüfung des Ergebnisses
SELECT node_path, name, content
FROM nodes_hierarchy
WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise\Datenbank';

commit;



-- -----------------------------------------------------------------------------------------------------------------------------
-- \Profile\APEX Developer 1.0.0\Expertise\SQL
-- -----------------------------------------------------------------------------------------------------------------------------

UPDATE nodes
SET content = '<p>> 20 Jahre Oracle SQL Erfahrung</p>
<p>Einrichtung von Schemata</p>
<p>Datenbanklinks, externe Tabellen, externe Funktionen</p>
<p>Analytische Funktionen</p>
<p>Hierarchische Queries</p>
<p>XML / SQL – Table Mapping</p>
<p>Tuning mittels:
<ul>
<li>Analyse des Execution-Plans</li>
<li>SQL Hints</li>
<li>Index Sichtbarkeit</li>
<li>Functional Indices</li>
</ul></p>'
WHERE id = (
    SELECT id
    FROM nodes_hierarchy
    WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise\SQL'
);

-- Überprüfung des Ergebnisses
SELECT node_path, name, content
FROM nodes_hierarchy
WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise\SQL';

commit;

-- -----------------------------------------------------------------------------------------------------------------------------
-- \Profile\APEX Developer 1.0.0\Expertise\PL/SQL
-- -----------------------------------------------------------------------------------------------------------------------------
UPDATE nodes
SET content = '<p>> 20 Jahre PL/SQL Erfahrung</p>
<p>SQL Generierung (z.B. Migrationsskripte, Views oder Programme)</p>
<p>Dynamisches Funktionen mit Cursor-Variablen</p>
<p>Autonome Transaktionen</p>
<p>Exception Handling</p>
<p>Umgang mit Pragmata</p>
<p>Verschlüsselung</p>
<p>Kurse bei Steven Feuerstein</p>'
WHERE id = (
    SELECT id
    FROM nodes_hierarchy
    WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise\PL/SQL'
);

-- Überprüfung des Ergebnisses
SELECT node_path, name, content
FROM nodes_hierarchy
WHERE node_path = '\Profile\APEX Developer 1.0.0\Expertise\PL/SQL';

commit;


-- -----------------------------------------------------------------------------------------------------------------------------
-- \Profile\APEX Developer 1.0.0\Projekte
-- -----------------------------------------------------------------------------------------------------------------------------

delete from nodes where parent_id =
(
  SELECT id
  FROM nodes_hierarchy 
  WHERE node_path = '\Profile\APEX Developer 1.0.0\Projekte'
)
;
 
select * from projekte
order by start_datum; 


INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
select
  h.id
, row_number() over(order by p.start_datum)
, p.projekt_name
, null
, null
, row_number() over(order by p.start_datum)  * 10
from projekte p
,    nodes_hierarchy h
where h.node_path = '\Profile\APEX Developer 1.0.0\Projekte'
order by p.start_datum 
;

commit;
  

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
select
  576 + row_number() over(order by p.start_datum)
, 'Name'
, p.projekt_name
, ' '
, '<h1 class="profil">@</h1>'
, 10
from projekte p
order by p.start_datum 
;

update nodes 
set format_content = '<h1 class="profil">@</h1>' 
, format_name = 'Projekt' 
where name = 'Name'
and id > 576
;

update nodes 
set content = replace(content,'-','<br/>-')

where name = 'Beschreibung'
and id > 576
;


update nodes 
SET content = 
    CASE 
        WHEN INSTR(content, '<br/>- ') > 0 THEN
            SUBSTR(content, 1, INSTR(content, '<br/>- ') - 1) || 
            '- ' || 
            SUBSTR(content, INSTR(content, '<br/>- ') + LENGTH('<br/>- '))
        ELSE
            content
    END
where name = 'Beschreibung'
and id > 576
;



update nodes 
set format_name = replace(format_name,'\','/')
, format_content = replace(format_content,'\','/')
;

commit;



INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
select
  576 + row_number() over(order by p.start_datum)
, 'Unternehmen'
, p.unternehmen
, null
, null
, 20
from projekte p
order by p.start_datum 
;

commit;

--delete nodes where name = 'Branche';

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
select
  576 + row_number() over(order by p.start_datum)
, 'Branche'
, p.branche
, null
, null
, 30
from projekte p
order by p.start_datum 
;

commit;


INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
select
  576 + row_number() over(order by p.start_datum)
, 'Start'
, to_char(p.start_datum, 'dd.mm.yyyy')
, null
, null
, 40
from projekte p
order by p.start_datum 
;

commit;


INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
select
  576 + row_number() over(order by p.start_datum)
, 'Ende'
, to_char(p.end_datum, 'dd.mm.yyyy')
, null
, null
, 50
from projekte p
order by p.start_datum 
;

commit;


INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
select
  576 + row_number() over(order by p.start_datum)
, 'Rolle'
, rolle
, null
, null
, 60
from projekte p
order by p.start_datum 
;

commit;


INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
select
  576 + row_number() over(order by p.start_datum)
, 'Beschreibung'
, beschreibung
, null
, null
, 70
from projekte p
order by p.start_datum 
;

commit;


INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
select
  576 + row_number() over(order by p.start_datum)
, 'Haupttechnologien'
, haupttechnologien
, null
, null
, 80
from projekte p
order by p.start_datum 
;

commit;

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
select
  576 + row_number() over(order by p.start_datum)
, 'Land'
, land
, null
, null
, 25
from projekte p
order by p.start_datum 
;

commit;
 
 
INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
select
  576 + row_number() over(order by p.start_datum)
, '#imagepath'
, image_path
, null
, null
, 90
from projekte p
order by p.start_datum 
;

commit; 



select
  576 + row_number() over(order by p.start_datum)
,p.*
from projekte p
order by p.start_datum 
;

select
 '<tr><td>'||p.projekt_name||' ('||start_datum||' - '||end_datum||')</td><td>Link: <br/>Autor:<br/></td></tr>'  x
from projekte p
order by p.start_datum desc
;




-- -----------------------------------------------------------------------------------------------------------------------------
-- Knoten für \APP\Impressum: 
-- -----------------------------------------------------------------------------------------------------------------------------

-- INSERT-Anweisungen für Unterknoten von "\Profile\APEX Developer 1.0.0\Titelseite"
INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq)
values (NULL, 'App', NULL, NULL, NULL, 20);

delete nodes 
where id = 
(select id FROM nodes_hierarchy WHERE node_path = '\App\Impressum')
;

INSERT INTO nodes (parent_id, name, content, format_name, format_content, seq, big_content)
SELECT id, 'Impressum', null, null, null, 20,
'
<impressum>

<h3> Webseiten-Betreiber und inhaltlich Verantwortlicher</h3>

<table class="impressum">
<tr><td>Name</td><td>Marcus Kühl</td></tr>
<tr><td>Anschrift</td><td>Odinstraße 24</br>10318 Berlin</td></tr>
<tr><td>Email</td><td>office.kuehl@poste.de</td></tr>
<tr><td>Telefon</td><td>0176 / 99 21 95 05</td></tr>
<tr><td>USTID</td><td>12345</td></tr>

</table>

<h3> Verwendete Abbildungen</h3>

<p></p>Alle verwendeten Fotographien unter dem Menü "Fotos" sind von mir. Die Abbildungen zu meinen Projekten entstammen der Wikimedia-Commons. </p>
<h4>Nachweise im Einzelnen:</h4> 

<table border="0" class="impressum" style="width:100pct;">
  <tr>
    <th>Projekt</th>
    <th>Quelle</th>
    <th>Titel</th>
    <th>Autor</th>
    <th>Lizenz</th>
  </tr>

  <tr>
    <td>Digitale Förderplattform</td>
    <td><a target="_blank" href="https://commons.wikimedia.org/wiki/File:Spitz_Weinberg_Singerriedl-3283.jpg">Link</a></td>
    <td>Spitz, Weinberg Singerriedl</td>
    <td>Isiwal</td>
    <td><a target="_blank" href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>

  <tr>
    <td>Pharmacovigilance Intelligence Tracking System</td>
    <td><a target="_blank" href="https://commons.wikimedia.org/wiki/File:Merck_Research_Laboratories.jpg">Link</a></td>
    <td>Merck Research Laboratories in South San Francisco, California</td>
    <td>Coolcaesar</td>
    <td><a target="_blank" href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>

  <tr>
    <td>Pharmacovigilance Reporting im ARISg Umfeld</td>
    <td><a target="_blank" href="https://commons.wikimedia.org/wiki/File:2015-10-04_Basel_Roche_Tower_0305.JPG">Link</a></td>
    <td>Basel, Schweiz</td>
    <td>Norbert Aepli, Switzerland</td>
    <td><a target="_blank" href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>

  <tr>
    <td>European Train Control System (ETCS)</td>
    <td><a target="_blank" href="https://commons.wikimedia.org/wiki/File:Siemens_Campus_Erlangen.jpg">Link</a></td>
    <td>Siemens Campus Erlangen (2023)</td>
    <td>Hans-Rudi der Letzte</td>
    <td><a target="_blank" href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>

  <tr>
    <td>Migration eines Pharmakovigilanz Reportingsystems</td>
    <td><a target="_blank" href="https://commons.wikimedia.org/wiki/File:2015-10-04_Basel_Roche_Tower_0305.JPG">Link</a></td>
    <td>Basel, Schweiz</td>
    <td>Norbert Aepli, Switzerland</td>
    <td><a target="_blank" href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>

  <tr>
    <td>Oracle Application Express Entwicklung im KVAI Umfeld</td>
    <td><a href="https://commons.wikimedia.org/wiki/File:M%C3%BCnchen_%E2%80%94_Elsenheimerstra%C3%9Fe_39_(Kassen%C3%A4rztliche_Vereinigung_Bayerns).jpg">Link</a></td>
    <td>Kassenärztliche Vereinigung Bayerns</td>
    <td>User:Mattes</td>
    <td><a href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>

  <tr>
    <td></td>
    <td><a target="_blank" href="https://commons.wikimedia.org/wiki/File:Heidelberger_Druckmaschinen_S_Printing_Horse_2007_by-RaBoe_01.jpg">Link</a></td>
    <td>Das S-Printing Horse</td>
    <td>Ra Boe</td>
    <td><a href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>

  <tr>
    <td>Weiterentwicklung der Teilsysteme Bill Presentation und Correspondence</td>
    <td><a target="_blank" href="https://commons.wikimedia.org/wiki/File:D-AHLD_(3315729683).jpg">Link</a></td>
    <td>Haj / Eddv 28-4-2007</td>
    <td>Björn Strey</td>
    <td><a href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>
  
  <tr>
    <td>Migration eines Pharmakovigilanz-Systems</td>
    <td><a target="_blank" href="https://commons.wikimedia.org/wiki/File:BI_5_Boehringer_Ingelheim.jpg">Link</a></td>
    <td>Verwaltungsgebäude von Boehringer Ingelheim</td>
    <td>SBA Architektur und Städtebau</td>
    <td><a target="_blank" href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>

  <tr>
    <td>Entwicklung einer Renderengine für PURUS Page Create</td>
    <td><a target="_blank" href="https://commons.wikimedia.org/wiki/File:Drupa_2012_HEIDELBERG_by-RaBoe_110.jpg">Link</a></td>
    <td>Bilder von der Drupa 2012</td>
    <td>Ra Boe / Wikipedia</td>
    <td><a target="_blank" href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>

  <tr>
    <td>Entwicklung des KVB Arztverzeichnisses</td>
    <td><a target="_blank" href="https://commons.wikimedia.org/wiki/File:M%C3%BCnchen_%E2%80%94_Elsenheimerstra%C3%9Fe_39_(Kassen%C3%A4rztliche_Vereinigung_Bayerns).jpg">Link</a></td>
    <td>Kassenärztliche Vereinigung Bayerns (Dienstgebäude am Sitz der Kassenärztlichen Vereinigung Bayerns Körperschaft des Öffentlichen Rechts)</td>
    <td>User:Mattes</td>
    <td><a target="_blank" href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>

  <tr>
    <td>Entwicklung eines CORBA Subscriptionservers</td>
    <td><a target="_blank" href="https://commons.wikimedia.org/wiki/File:Heidelberger_Druckmaschinen_S_Printing_Horse_2007_by-RaBoe_01.jpg">Link</a></td>
    <td>Das S-Printing Horse</td>
    <td>Ra Boe</td>
    <td><a target="_blank" href="https://en.wikipedia.org/wiki/en:Creative_Commons">Creative Commons</a></td>
  </tr>

  <tr>
    <td>Instandhaltung und Betreuung einer Entwicklungsumgebung</td>
    <td><a target="_blank" href="https://upload.wikimedia.org/wikipedia/commons/9/90/Frankfurter_Sparkasse.jpg">Link</a></td>
    <td>Leuchtreklame der Frankfurter Sparkasse an der Filiale in Frankfurt-Bornheim. Selbst fotografiert am 20. September 2006.</td>
    <td>Metroskop at German Wikipedia</td>
    <td>public domain </td>
  </tr>

</table>

<div style="text-align: right;">
   <p></br></br>
   <a href="javascript:history.back()"><b>Zurück</b></a>
   </p>
 </div>

</impressum>
'
FROM nodes_hierarchy WHERE node_path = '\App';


commit;


begin
 pck_nodes.generate_node_inserts;
end;
/

